"""empty message

Revision ID: 44ad5da919f6
Revises: 4b5c43994aa0
Create Date: 2024-04-29 06:12:48.298405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ad5da919f6'
down_revision = '4b5c43994aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
